# Generated by Django 3.0.9 on 2020-08-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('number_seats', models.IntegerField()),
                ('number_pc', models.IntegerField()),
            ],
        ),
    ]
