# Generated by Django 3.0.9 on 2020-08-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='number_pc',
            new_name='anzahl_pc',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='number_seats',
            new_name='anzahl_plaetze',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='raumID',
        ),
    ]
