# Generated by Django 3.0.9 on 2020-08-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Unterrichtsraum', 'Unterrichtsraum'), ('Hörsaal', 'Hörsaal'), ('PC-Raum', 'PC-Raum'), ('Selbstlernecke', 'Selbstlernecke')], max_length=15),
        ),
    ]
